// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzNuoyt0lOha9h_qqgD1nYW_eKgiPWT8',
    appId: '1:762448730547:web:88fa7d75d34f30b19893c6',
    messagingSenderId: '762448730547',
    projectId: 'palpipatrol',
    authDomain: 'palpipatrol.firebaseapp.com',
    storageBucket: 'palpipatrol.appspot.com',
    measurementId: 'G-Z97TXSR1G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWFtHsppELtxc-b5obhyy382yi3mgcPo',
    appId: '1:762448730547:android:6647091f0ad2eb0e9893c6',
    messagingSenderId: '762448730547',
    projectId: 'palpipatrol',
    storageBucket: 'palpipatrol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpv2XI6KvVeHvH5iojA-62r5Ew9q-TMho',
    appId: '1:762448730547:ios:66fbcad24e96eeb79893c6',
    messagingSenderId: '762448730547',
    projectId: 'palpipatrol',
    storageBucket: 'palpipatrol.appspot.com',
    iosClientId: '762448730547-brbldgd4ncqgd8s9c7r5df0b23gp0gsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.palpipatrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpv2XI6KvVeHvH5iojA-62r5Ew9q-TMho',
    appId: '1:762448730547:ios:66fbcad24e96eeb79893c6',
    messagingSenderId: '762448730547',
    projectId: 'palpipatrol',
    storageBucket: 'palpipatrol.appspot.com',
    iosClientId: '762448730547-brbldgd4ncqgd8s9c7r5df0b23gp0gsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.palpipatrol',
  );
}
